# ppo_train_prompts.py

# Diverse training prompts - 500+ prompts for robust PPO training
training_prompts = [
    # ============ AI/ML Concepts (100 prompts) ============
    "Explain artificial intelligence in simple terms:",
    "What are the ethical concerns with AI?",
    "Describe how neural networks learn:",
    "What is the difference between AI and ML?",
    "How does reinforcement learning work?",
    "What are transformers in deep learning?",
    "Explain the attention mechanism:",
    "What is supervised learning?",
    "Describe unsupervised learning:",
    "What is deep learning?",
    "How do GANs generate images?",
    "What is natural language processing?",
    "Explain computer vision applications:",
    "What is transfer learning?",
    "Describe the bias-variance tradeoff:",
    "How does backpropagation work?",
    "What are convolutional neural networks?",
    "Explain overfitting in machine learning:",
    "What are recommendation systems?",
    "Describe the future of AI:",
    "What is a loss function in ML?",
    "Explain gradient descent optimization:",
    "What are hyperparameters in ML?",
    "Describe model evaluation metrics:",
    "What is cross-validation?",
    "Explain regularization techniques:",
    "What is feature engineering?",
    "Describe dimensionality reduction:",
    "What is ensemble learning?",
    "Explain the curse of dimensionality:",
    "What is online learning?",
    "Describe reinforcement learning algorithms:",
    "What is Markov Decision Process?",
    "Explain Q-learning:",
    "What is policy gradient?",
    "Describe imitation learning:",
    "What is meta-learning?",
    "Explain few-shot learning:",
    "What is self-supervised learning?",
    "Describe contrastive learning:",
    "What is federated learning?",
    "Explain differential privacy in ML:",
    "What is explainable AI?",
    "Describe fairness in machine learning:",
    "What is algorithmic bias?",
    "Explain data augmentation:",
    "What is synthetic data generation?",
    "Describe ML model deployment:",
    "What is MLOps?",
    "Explain AI governance:",
    "What is active learning?",
    "Describe semi-supervised learning:",
    "What is multi-task learning?",
    "Explain graph neural networks:",
    "What are recurrent neural networks?",
    "Describe long short-term memory networks:",
    "What are autoencoders?",
    "Explain variational autoencoders:",
    "What are diffusion models?",
    "Describe neural style transfer:",
    "What is object detection?",
    "Explain image segmentation:",
    "What is named entity recognition?",
    "Describe sentiment analysis:",
    "What is text summarization?",
    "Explain question answering systems:",
    "What are word embeddings?",
    "Describe BERT architecture:",
    "What is GPT?",
    "Explain the transformer architecture:",
    "What is multi-head attention?",
    "Describe positional encoding:",
    "What is layer normalization?",
    "Explain residual connections:",
    "What is batch normalization?",
    "Describe dropout regularization:",
    "What is early stopping?",
    "Explain learning rate scheduling:",
    "What is momentum in optimization?",
    "Describe Adam optimizer:",
    "What is SGD with momentum?",
    "Explain weight decay:",
    "What is gradient clipping?",
    "Describe the vanishing gradient problem:",
    "What is the exploding gradient problem?",
    "Explain the ReLU activation function:",
    "What are sigmoid and tanh functions?",
    "Describe softmax activation:",
    "What is a confusion matrix?",
    "Explain precision and recall:",
    "What is F1 score?",
    "Describe ROC curves and AUC:",
    "What is mean squared error?",
    "Explain cross-entropy loss:",
    "What is hinge loss?",
    "Describe k-means clustering:",
    "What is hierarchical clustering?",
    "Explain principal component analysis:",
    "What is t-SNE?",
    "Describe association rule learning:",
    "What is Apriori algorithm?",
    "Explain decision trees:",
    "What are random forests?",
    "Describe gradient boosting:",
    "What is XGBoost?",
    "Explain support vector machines:",
    "What is kernel trick?",
    
    # ============ Programming/Technical (100 prompts) ============
    "Explain object-oriented programming:",
    "What are design patterns?",
    "Describe version control systems:",
    "What is agile methodology?",
    "How do databases work?",
    "Explain REST APIs:",
    "What is microservices architecture?",
    "Describe containerization:",
    "What is DevOps?",
    "Explain cloud computing:",
    "How does encryption work?",
    "What are blockchain technologies?",
    "Describe cybersecurity best practices:",
    "What is quantum computing?",
    "Explain parallel processing:",
    "How do compilers work?",
    "What is memory management?",
    "Describe operating systems:",
    "What is network programming?",
    "Explain web development frameworks:",
    "How do mobile apps work?",
    "What is game development?",
    "Describe embedded systems:",
    "What is IoT?",
    "Explain robotics programming:",
    "How does computer graphics work?",
    "What is computer architecture?",
    "Describe algorithm complexity:",
    "What is data structures?",
    "Explain software testing:",
    "What is continuous integration?",
    "Describe continuous deployment:",
    "What is infrastructure as code?",
    "Explain serverless computing:",
    "What is edge computing?",
    "Describe distributed systems:",
    "What is Apache Spark?",
    "Explain Hadoop ecosystem:",
    "What is MapReduce?",
    "Describe NoSQL databases:",
    "What is SQL?",
    "Explain relational databases:",
    "What is ACID compliance?",
    "Describe CAP theorem:",
    "What is GraphQL?",
    "Explain WebSockets:",
    "What is HTTP/2 and HTTP/3?",
    "Describe DNS resolution:",
    "What is TCP/IP?",
    "Explain UDP protocol:",
    "What is OAuth?",
    "Describe JWT authentication:",
    "What is SAML?",
    "Explain single sign-on:",
    "What is two-factor authentication?",
    "Describe SSL/TLS:",
    "What is a VPN?",
    "Explain firewall architecture:",
    "What is intrusion detection?",
    "Describe penetration testing:",
    "What is secure coding?",
    "Explain buffer overflow:",
    "What is SQL injection?",
    "Describe cross-site scripting:",
    "What is CSRF?",
    "Explain Docker:",
    "What is Kubernetes?",
    "Describe orchestration:",
    "What is Ansible?",
    "Explain Terraform:",
    "What is Jenkins?",
    "Describe GitLab CI/CD:",
    "What is GitHub Actions?",
    "Explain Python decorators:",
    "What is multithreading?",
    "Describe asynchronous programming:",
    "What are coroutines?",
    "Explain functional programming:",
    "What is immutability?",
    "Describe pure functions:",
    "What is lambda calculus?",
    "Explain recursion:",
    "What is dynamic programming?",
    "Describe greedy algorithms:",
    "What is graph theory?",
    "Explain BFS and DFS:",
    "What is Dijkstra's algorithm?",
    "Describe A* search:",
    "What is the knapsack problem?",
    "Explain NP-completeness:",
    "What is Big O notation?",
    "Describe amortized analysis:",
    "What is software architecture?",
    "Explain MVC pattern:",
    "What is MVP pattern?",
    "Describe MVVM pattern:",
    "What is event-driven architecture?",
    "Explain domain-driven design:",
    "What is test-driven development?",
    "Describe behavior-driven development:",
    
    # ============ Science/Education (100 prompts) ============
    "Explain quantum mechanics basics:",
    "What is relativity theory?",
    "Describe the scientific method:",
    "How does evolution work?",
    "What is genetics?",
    "Explain cellular biology:",
    "Describe the human brain:",
    "What is climate change?",
    "Explain renewable energy:",
    "How do vaccines work?",
    "What is the immune system?",
    "Describe human anatomy:",
    "What is astronomy?",
    "Explain the solar system:",
    "How do black holes form?",
    "What is chemistry?",
    "Describe the periodic table:",
    "What is physics?",
    "Explain Newton's laws:",
    "How does electricity work?",
    "What is magnetism?",
    "Describe geology:",
    "What are tectonic plates?",
    "Explain weather patterns:",
    "How do ecosystems work?",
    "What is biodiversity?",
    "Describe environmental science:",
    "What is psychology?",
    "Explain cognitive science:",
    "How do we learn?",
    "What is memory formation?",
    "Describe neural plasticity:",
    "What is consciousness?",
    "Explain sleep cycles:",
    "What are emotions?",
    "Describe behavioral conditioning:",
    "What is personality psychology?",
    "Explain developmental psychology:",
    "What is social psychology?",
    "Describe abnormal psychology:",
    "What is biochemistry?",
    "Explain molecular biology:",
    "What is DNA replication?",
    "Describe protein synthesis:",
    "What is gene expression?",
    "Explain CRISPR technology:",
    "What are stem cells?",
    "Describe epigenetics:",
    "What is bioinformatics?",
    "Explain synthetic biology:",
    "What is ecology?",
    "Describe food chains:",
    "What is conservation biology?",
    "Explain marine biology:",
    "What is botany?",
    "Describe zoology:",
    "What is microbiology?",
    "Explain virology:",
    "What is bacteriology?",
    "Describe mycology:",
    "What is astronomy?",
    "Explain cosmology:",
    "What is astrophysics?",
    "Describe the Big Bang theory:",
    "What are exoplanets?",
    "Explain stellar evolution:",
    "What are galaxies?",
    "Describe dark matter:",
    "What is dark energy?",
    "Explain gravitational waves:",
    "What is quantum entanglement?",
    "Describe Heisenberg uncertainty principle:",
    "What is Schrödinger's equation?",
    "Explain quantum superposition:",
    "What is particle physics?",
    "Describe the standard model:",
    "What are quarks?",
    "Explain string theory:",
    "What is loop quantum gravity?",
    "Describe thermodynamics:",
    "What is entropy?",
    "Explain the laws of thermodynamics:",
    "What is fluid dynamics?",
    "Describe aerodynamics:",
    "What is electromagnetism?",
    "Explain Maxwell's equations:",
    "What is optics?",
    "Describe quantum optics:",
    "What is nanotechnology?",
    "Explain material science:",
    "What is metallurgy?",
    "Describe crystallography:",
    "What is polymer science?",
    "Explain organic chemistry:",
    "What is inorganic chemistry?",
    "Describe analytical chemistry:",
    "What is physical chemistry?",
    "Explain spectroscopy:",
    "What is chromatography?",
    
    # ============ Creative/Open-ended (100 prompts) ============
    "Write a short poem about technology:",
    "Create a story about a robot learning emotions:",
    "Describe a perfect future city:",
    "Imagine a conversation between AI and human:",
    "Write a dialogue about ethics in technology:",
    "Create a fictional technology invention:",
    "Describe how society might change with advanced AI:",
    "Write about the impact of automation on jobs:",
    "Imagine solving climate change with technology:",
    "Create a character who is an AI researcher:",
    "Write a letter to future generations about AI:",
    "Describe a day in life with personal AI assistants:",
    "Imagine discovering alien technology:",
    "Write about the ethics of AI in healthcare:",
    "Create a plot for a sci-fi movie about AI:",
    "Describe the ideal education system with AI:",
    "Write about privacy in the digital age:",
    "Imagine AI in art and creativity:",
    "Describe a world where humans and AI coexist:",
    "Write about the philosophical implications of AI:",
    "Create a futuristic transportation system:",
    "Describe AI in space exploration:",
    "Write about digital currencies and AI:",
    "Imagine AI solving world hunger:",
    "Describe sustainable technology solutions:",
    "Write about the role of AI in democracy:",
    "Create a scenario where AI prevents a disaster:",
    "Describe the future of work with AI:",
    "Write about human-AI collaboration:",
    "Imagine the next technological revolution:",
    "Write a story about a machine that can read memories:",
    "Describe a society without any technology:",
    "Imagine a conversation between Einstein and an AI:",
    "Write about an AI that develops consciousness:",
    "Create a poem about the internet:",
    "Describe a virtual reality world:",
    "Write about a hacker in a cyberpunk city:",
    "Imagine teleportation becomes reality:",
    "Describe a world with flying cars:",
    "Write about a brain-computer interface:",
    "Create a story about digital immortality:",
    "Describe the first contact with AI:",
    "Write about a robot rebellion:",
    "Imagine humans uploading their minds:",
    "Describe a society run by algorithms:",
    "Write about the last human programmer:",
    "Create a dialogue between two different AIs:",
    "Describe a museum of obsolete technology:",
    "Write about time travel through computers:",
    "Imagine a world without screens:",
    "Describe AI-powered art gallery:",
    "Write about a musician who collaborates with AI:",
    "Create a story about AI-written novels:",
    "Describe AI in fashion design:",
    "Write about AI-generated movies:",
    "Imagine AI composing symphonies:",
    "Describe robot sports competitions:",
    "Write about AI in culinary arts:",
    "Create a story about AI therapists:",
    "Describe AI in architecture:",
    "Write about AI-designed buildings:",
    "Imagine AI urban planning:",
    "Describe AI in agriculture:",
    "Write about vertical farming with AI:",
    "Create a story about AI conservationists:",
    "Describe AI monitoring endangered species:",
    "Write about AI in ocean exploration:",
    "Imagine AI archaeologists:",
    "Describe AI restoring historical artifacts:",
    "Write about AI in museums:",
    "Create a story about AI historians:",
    "Describe AI preserving languages:",
    "Write about AI translating ancient texts:",
    "Imagine AI in journalism:",
    "Describe AI-written news articles:",
    "Write about AI fact-checkers:",
    "Create a story about AI lawyers:",
    "Describe AI in courtroom:",
    "Write about AI judges:",
    "Imagine AI in police work:",
    "Describe AI solving cold cases:",
    "Write about AI predictive policing:",
    "Create a story about AI firefighters:",
    "Describe AI in disaster response:",
    "Write about AI search and rescue:",
    "Imagine AI in military:",
    "Describe AI in peacekeeping:",
    "Write about AI weapons:",
    "Create a story about AI diplomats:",
    "Describe AI in international relations:",
    "Write about AI negotiating treaties:",
    "Imagine AI in sports:",
    "Describe AI coaching:",
    "Write about AI referees:",
    "Create a story about AI athletes:",
    "Describe AI in exercise and fitness:",
    "Write about AI nutritionists:",
    "Imagine AI in mental health:",
    "Describe AI counselors:",
    "Write about AI support groups:",
    
    # ============ Practical/Instructional (100 prompts) ============
    "How to learn programming effectively:",
    "Steps to build a machine learning model:",
    "Guide to starting a tech career:",
    "How to debug code efficiently:",
    "Tips for effective team collaboration:",
    "Best practices for data analysis:",
    "How to give a technical presentation:",
    "Steps for scientific research:",
    "Guide to writing technical documentation:",
    "How to manage complex projects:",
    "Tips for effective problem solving:",
    "Best practices for code review:",
    "How to stay updated with technology:",
    "Steps to create a portfolio project:",
    "Guide to technical interviews:",
    "How to mentor junior developers:",
    "Tips for remote work productivity:",
    "Best practices for software design:",
    "How to handle technical debt:",
    "Steps for system architecture design:",
    "Guide to performance optimization:",
    "How to conduct user research:",
    "Tips for effective communication:",
    "Best practices for security:",
    "How to plan a product roadmap:",
    "Steps for quality assurance:",
    "Guide to open source contributions:",
    "How to balance innovation and stability:",
    "Tips for leadership in tech:",
    "Best practices for continuous learning:",
    "How to write clean code:",
    "Steps for refactoring legacy code:",
    "Guide to writing unit tests:",
    "How to perform code profiling:",
    "Tips for database optimization:",
    "Best practices for API design:",
    "How to handle errors gracefully:",
    "Steps for logging and monitoring:",
    "Guide to system scalability:",
    "How to design for high availability:",
    "Tips for disaster recovery planning:",
    "Best practices for backup strategies:",
    "How to conduct security audits:",
    "Steps for vulnerability assessment:",
    "Guide to incident response:",
    "How to create a tech resume:",
    "Tips for networking in tech industry:",
    "Best practices for job interviews:",
    "How to negotiate salary:",
    "Steps for career advancement:",
    "Guide to personal branding:",
    "How to write a technical blog:",
    "Tips for creating coding tutorials:",
    "Best practices for public speaking:",
    "How to contribute to GitHub:",
    "Steps for starting a tech blog:",
    "Guide to building a personal website:",
    "How to create a tech portfolio:",
    "Tips for freelance work:",
    "Best practices for client management:",
    "How to price your services:",
    "Steps for starting a tech company:",
    "Guide to finding co-founders:",
    "How to pitch to investors:",
    "Tips for product-market fit:",
    "Best practices for user acquisition:",
    "How to build an MVP:",
    "Steps for product iteration:",
    "Guide to scaling a startup:",
    "How to manage startup finances:",
    "Tips for hiring talent:",
    "Best practices for company culture:",
    "How to create user personas:",
    "Steps for user journey mapping:",
    "Guide to A/B testing:",
    "How to analyze user feedback:",
    "Tips for feature prioritization:",
    "Best practices for UX design:",
    "How to create wireframes:",
    "Steps for prototyping:",
    "Guide to usability testing:",
    "How to design for accessibility:",
    "Tips for responsive design:",
    "Best practices for mobile design:",
    "How to create design systems:",
    "Steps for color theory in design:",
    "Guide to typography:",
    "How to use whitespace effectively:",
    "Tips for visual hierarchy:",
    "Best practices for information architecture:",
    "How to create compelling content:",
    "Steps for content strategy:",
    "Guide to SEO optimization:",
    "How to measure content performance:",
    "Tips for social media marketing:",
    "Best practices for email campaigns:",
    "How to analyze marketing metrics:",
    "Steps for growth hacking:",
    
    # ============ Philosophical/Ethical (60 prompts) ============
    "What is consciousness?",
    "Discuss free will vs determinism:",
    "What makes us human?",
    "Discuss the ethics of AI decision-making:",
    "What is the meaning of intelligence?",
    "Discuss the singularity hypothesis:",
    "What are human rights in digital age?",
    "Discuss automation and human purpose:",
    "What is ethical technology design?",
    "Discuss AI and moral responsibility:",
    "What is the future of privacy?",
    "Discuss bias in algorithmic systems:",
    "What is digital ethics?",
    "Discuss the social impact of AI:",
    "What is technological determinism?",
    "Discuss AI and creativity:",
    "What is the value of human labor?",
    "Discuss existential risks of AI:",
    "What is human dignity in AI era?",
    "Discuss the philosophy of technology:",
    "What is the nature of reality?",
    "Discuss the mind-body problem:",
    "What is the self?",
    "Discuss the ethics of genetic engineering:",
    "What is moral relativism?",
    "Discuss utilitarianism vs deontology:",
    "What is virtue ethics?",
    "Discuss animal rights:",
    "What is environmental ethics?",
    "Discuss bioethics:",
    "What is the value of biodiversity?",
    "Discuss intergenerational justice:",
    "What is the precautionary principle?",
    "Discuss corporate responsibility:",
    "What is fair trade?",
    "Discuss economic inequality:",
    "What is distributive justice?",
    "Discuss universal basic income:",
    "What is the nature of happiness?",
    "Discuss meaning and purpose:",
    "What is existentialism?",
    "Discuss Stoicism:",
    "What is Buddhist philosophy?",
    "Discuss Eastern vs Western philosophy:",
    "What is epistemology?",
    "Discuss the nature of knowledge:",
    "What is skepticism?",
    "Discuss empiricism vs rationalism:",
    "What is metaphysics?",
    "Discuss ontology:",
    "What is causality?",
    "Discuss space and time:",
    "What is aesthetics?",
    "Discuss the nature of beauty:",
    "What is art?",
    "Discuss postmodernism:",
    "What is structuralism?",
    "Discuss critical theory:",
    "What is feminism?",
    "Discuss postcolonialism:",
    
    # ============ Current Events/Trends (60 prompts) ============
    "Discuss recent AI breakthroughs:",
    "What are current trends in ML?",
    "Discuss the impact of large language models:",
    "What is the state of AI regulation?",
    "Discuss AI in healthcare advancements:",
    "What are autonomous systems developments?",
    "Discuss AI in climate science:",
    "What are quantum computing advances?",
    "Discuss edge computing trends:",
    "What is the metaverse?",
    "Discuss Web3 and blockchain:",
    "What are digital twins?",
    "Discuss AI in education:",
    "What are smart city technologies?",
    "Discuss 5G/6G impact:",
    "What are sustainable tech innovations?",
    "Discuss space technology advances:",
    "What are biotechnology trends?",
    "Discuss digital health:",
    "What are future computing paradigms?",
    "Discuss the rise of remote work:",
    "What is the gig economy?",
    "Discuss digital transformation:",
    "What is Industry 4.0?",
    "Discuss supply chain innovation:",
    "What are electric vehicles trends?",
    "Discuss renewable energy storage:",
    "What is carbon capture technology?",
    "Discuss nuclear fusion developments:",
    "What are advanced materials?",
    "Discuss nanotechnology applications:",
    "What is precision medicine?",
    "Discuss gene therapy advances:",
    "What are mRNA vaccines?",
    "Discuss CRISPR breakthroughs:",
    "What is longevity research?",
    "Discuss brain-computer interfaces:",
    "What is neurotechnology?",
    "Discuss mental health tech:",
    "What is telemedicine?",
    "Discuss wearable technology:",
    "What is augmented reality?",
    "Discuss virtual reality:",
    "What is mixed reality?",
    "Discuss haptic technology:",
    "What is voice technology?",
    "Discuss computer vision applications:",
    "What is facial recognition?",
    "Discuss surveillance technology:",
    "What is biometrics?",
    "Discuss cybersecurity threats:",
    "What is ransomware?",
    "Discuss zero-trust architecture:",
    "What is DevSecOps?",
    "Discuss cloud-native technologies:",
    "What is service mesh?",
    "Discuss chaos engineering:",
    "What is site reliability engineering?",
    "Discuss platform engineering:",
    "What is FinOps?",
]


# Separate set of evaluation prompts (not used during training) - 200+ prompts
evaluation_prompts = [
    # ============ Technical Evaluation (50 prompts) ============
    "Explain how a CPU processes instructions:",
    "What is the difference between HTTP and HTTPS?",
    "Describe how a search engine ranks pages:",
    "How does machine translation work?",
    "What are the principles of good UI design?",
    "Explain how cryptocurrencies maintain security:",
    "Describe the process of software development:",
    "What is the role of an operating system kernel?",
    "How do compilers optimize code?",
    "Explain database normalization:",
    "What is the difference between TCP and UDP?",
    "How does RAID storage work?",
    "Explain the OSI model layers:",
    "What is virtual memory?",
    "Describe how garbage collection works:",
    "How do load balancers distribute traffic?",
    "Explain CDN architecture:",
    "What is the difference between HTTP/1.1 and HTTP/2?",
    "How does SSH encryption work?",
    "Describe OAuth 2.0 flow:",
    "What is the difference between REST and GraphQL?",
    "How do message queues work?",
    "Explain event sourcing pattern:",
    "What is CQRS?",
    "Describe how session management works in web apps:",
    "How do browser rendering engines work?",
    "Explain CSS specificity:",
    "What is the difference between cookies and localStorage?",
    "How does JavaScript event loop work?",
    "Describe React's virtual DOM:",
    "What is Angular's change detection?",
    "Explain Vue's reactivity system:",
    "How does Python's GIL affect threading?",
    "What is the difference between Java and JavaScript?",
    "Explain how Ruby on Rails conventions work:",
    "What is PHP's role in web development?",
    "Describe Go's concurrency model:",
    "How does Rust's ownership system work?",
    "Explain Swift's optionals:",
    "What is Kotlin's coroutines?",
    "How does TypeScript improve JavaScript?",
    "Describe SQL indexing strategies:",
    "What is the difference between SQL and NoSQL?",
    "Explain MongoDB's document model:",
    "How does Cassandra achieve high availability?",
    "What is Redis caching strategy?",
    "Describe Elasticsearch inverted index:",
    "How does Neo4j graph traversal work?",
    "Explain blockchain consensus mechanisms:",
    "What is proof of stake vs proof of work?",
    
    # ============ Scientific Evaluation (50 prompts) ============
    "Explain photosynthesis step by step:",
    "What causes earthquakes?",
    "How does the greenhouse effect work?",
    "Describe the water cycle in detail:",
    "What is DNA replication?",
    "Explain the theory of plate tectonics:",
    "How do vaccines stimulate immunity?",
    "What is the structure of an atom?",
    "Describe the human digestive system:",
    "Explain the process of mitosis:",
    "How does natural selection drive evolution?",
    "What causes volcanic eruptions?",
    "Explain the formation of fossils:",
    "How do neurons transmit signals?",
    "Describe the endocrine system:",
    "What is the cardiovascular system?",
    "Explain how kidneys filter blood:",
    "How does the liver detoxify the body?",
    "Describe the respiratory system:",
    "What is the musculoskeletal system?",
    "Explain how antibiotics work:",
    "What causes antibiotic resistance?",
    "Describe viral replication:",
    "How do prions cause disease?",
    "Explain the human microbiome:",
    "What is genetic drift?",
    "Describe Hardy-Weinberg equilibrium:",
    "How does speciation occur?",
    "Explain phylogenetics:",
    "What is cladistics?",
    "Describe cell division stages:",
    "How does apoptosis work?",
    "Explain cell signaling pathways:",
    "What are ion channels?",
    "Describe membrane transport:",
    "How does ATP power cellular processes?",
    "Explain metabolic pathways:",
    "What is glycolysis?",
    "Describe the Krebs cycle:",
    "How does oxidative phosphorylation work?",
    "Explain photosynthesis light reactions:",
    "What is the Calvin cycle?",
    "Describe plant transpiration:",
    "How do stomata regulate gas exchange?",
    "Explain plant hormones:",
    "What is photoperiodism?",
    "Describe animal behavior imprinting:",
    "How do birds navigate during migration?",
    "Explain echolocation in bats:",
    "What is bioluminescence?",
    
    # ============ Philosophical/Complex Evaluation (50 prompts) ============
    "Discuss the ethical implications of genetic engineering:",
    "What does it mean for an AI to be conscious?",
    "How should society regulate powerful AI systems?",
    "Discuss the balance between innovation and safety:",
    "What are the long-term societal impacts of automation?",
    "How do we define intelligence across different species?",
    "Discuss the role of technology in education reform:",
    "What ethical considerations exist for brain-computer interfaces?",
    "How can technology address climate change effectively?",
    "Discuss the future of human identity in digital age:",
    "What is the nature of truth in the digital era?",
    "Discuss the ethics of predictive policing:",
    "How should we regulate social media algorithms?",
    "What are the implications of deepfakes for society?",
    "Discuss digital addiction and mental health:",
    "What is the value of privacy in modern society?",
    "Discuss the ethics of autonomous weapons:",
    "How should we approach AI rights?",
    "What is the responsibility of tech companies?",
    "Discuss the digital divide and inequality:",
    "What is the role of government in technology regulation?",
    "Discuss the ethics of data collection:",
    "How should consent work in digital spaces?",
    "What are the implications of facial recognition?",
    "Discuss the ethics of predictive analytics:",
    "How can we ensure algorithmic fairness?",
    "What is the future of democracy in AI age?",
    "Discuss information warfare and cybersecurity:",
    "How should social media handle misinformation?",
    "What is the ethics of AI in hiring?",
    "Discuss AI in criminal justice:",
    "How should we regulate AI in healthcare?",
    "What are the ethics of AI in education?",
    "Discuss the future of human-AI relationships:",
    "How might AI change the nature of work?",
    "What is the role of creativity in AI age?",
    "Discuss AI and human enhancement:",
    "What are the ethics of life extension technology?",
    "How should we approach human cloning?",
    "Discuss the ethics of synthetic biology:",
    "What are the implications of germline editing?",
    "Discuss the nature of consciousness in animals:",
    "What is the ethical status of artificial life?",
    "How should we value biodiversity?",
    "Discuss the ethics of space colonization:",
    "What are our obligations to future generations?",
    "Discuss interplanetary contamination risks:",
    "How should we govern space resources?",
    "What is the ethics of terraforming?",
    "Discuss the search for extraterrestrial intelligence:",
    
    # ============ Creative/Scenario-based Evaluation (50 prompts) ============
    "Write a short dialogue between two scientists debating AI ethics:",
    "Describe a world where renewable energy is 100% adopted:",
    "Imagine explaining the internet to someone from 1800s:",
    "Create a story about an AI discovering human emotions:",
    "Write a persuasive argument for space exploration:",
    "Describe how technology could solve world hunger:",
    "Imagine a conversation about privacy in 2050:",
    "Write about the challenges of interplanetary travel:",
    "Describe a day in a fully automated smart home:",
    "Create a futuristic medical breakthrough scenario:",
    "Write about a world without passwords:",
    "Imagine a society where robots do all manual labor:",
    "Describe a classroom of the future:",
    "Write about the last library on Earth:",
    "Create a story about digital archaeology:",
    "Imagine a world where memories can be traded:",
    "Describe a vacation in virtual reality:",
    "Write about a therapist for AI systems:",
    "Create a dialogue between humans and uploaded minds:",
    "Imagine a city built on an ocean platform:",
    "Describe a wildlife preserve on Mars:",
    "Write about an AI historian of the 21st century:",
    "Create a story about a time capsule from 2024:",
    "Imagine a fashion show featuring AI-designed clothing:",
    "Describe a restaurant run entirely by robots:",
    "Write about a sports league for androids:",
    "Create a music festival featuring AI musicians:",
    "Imagine a movie written, directed, and scored by AI:",
    "Describe a video game that creates itself:",
    "Write about a museum of failed technologies:",
    "Create a story about a sentient building:",
    "Imagine a conversation with your house AI:",
    "Describe a car that predicts accidents:",
    "Write about a farm managed entirely by drones:",
    "Create a story about a forest monitored by AI:",
    "Imagine ocean cleanup technology of the future:",
    "Describe a carbon-negative power plant:",
    "Write about fusion energy becoming reality:",
    "Create a scenario where we mine asteroids:",
    "Imagine a space elevator construction project:",
    "Describe daily life in a lunar colony:",
    "Write about the first baby born on Mars:",
    "Create a story about finding alien microbes:",
    "Imagine first contact with intelligent aliens:",
    "Describe translating an alien language:",
    "Write about humanity becoming a spacefaring civilization:",
    "Create a dialogue about preserving Earth from space:",
    "Imagine a galactic federation of planets:",
    "Describe the discovery of a Dyson sphere:",
    "Write about the heat death of the universe:",
]
